name = "Piccolo"
uuid = "c4671d76-df94-11ed-2057-43d4fd632fad"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]
version = "0.1.0"

[deps]
IterativeLearningControl = "55efb022-e1be-4044-9089-57a478d003fb"
NamedTrajectories = "538bc3a1-5ab9-4fc3-b776-35ca1e893e08"
QuantumCollocation = "0dc23a59-5ffb-49af-b6bd-932a8ae77adf"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TrajectoryIndexingUtils = "6dad8b7f-dd9a-4c28-9b70-85b9a079bfc8"

[compat]
julia = "1.8"
Reexport = "1.2"
TrajectoryIndexingUtils = "0.1"
NamedTrajectories = "0.1"
QuantumCollocation = "0.1"
IterativeLearningControl = "0.1"